version: '3'

services:
  web-main:
    build:
      context: .
      dockerfile: .docker/web-main/Dockerfile
    volumes:
      - .env:/root/.env:ro
    restart: always
    depends_on:
      - minio

  web-admin:
    build:
      context: ./admin-ui
      dockerfile: ../.docker/web-admin/Dockerfile
    volumes:
      - .env:/app/.env:ro
    restart: always
    depends_on:
      - web-main

  minio:
    image: quay.io/minio/minio:RELEASE.2021-10-02T16-31-05Z
    command: server --console-address ":9001" /data/minio
    expose:
      - "9000"
      - "9001"
    environment:
      MINIO_ROOT_USER: "${MINIO_USER}"
      MINIO_ROOT_PASSWORD: "${MINIO_PASS}"
    volumes:
      - ./.docker/minio/:/data/minio
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9000/minio/health/live" ]
      interval: 30s
      timeout: 20s
      retries: 3
    restart: always

  nginx:
    image: nginx:alpine
    volumes:
      - .docker/nginx/config/brucifer.conf:/etc/nginx/conf.d/default.conf:ro
    restart: always
